[package]
name = "algs4"
version = "0.1.0"
edition = "2024"

[dependencies]
aho-corasick = "1.1.3"
bitvec = "1.0.1"
clap = "4.5.34"
dary_heap = "0.3.7"
ethnum = "1.5.1"
fnv = "1.0.7"
likely_stable = "0.1.3"
ordered-float = "5.0.0"
rand = "0.9.0"

[profile.release]
lto = "fat"
codegen-units = 1
